version: '3.1'

services:
    flowise:
        image: flowiseai/flowise
        restart: always
        env_file:
          - ./envs/flowise.env
        ports:
            - '3000:3000'
        volumes:
            - ~/.flowise:/root/.flowise
        command: /bin/sh -c "sleep 3; flowise start"
    backend:
      container_name: llm-cv-scanner-backend
      image: llm-cv-scanner-backend
      restart: always
      environment:
        - PORT=5000
      build:
          context: backend
          dockerfile: dockerfile
      ports:
          - '5000:5000'
    frontend:
      image: llm-cv-scanner-dashboard
      container_name: llm-cv-scanner-dashboard
      restart: always
      build:
        context: frontend/llm-cv-scanner-dashboard
        dockerfile: dockerfile
      ports:
        - '8080:8080'
      command: npm start
    minio:
      command: server /data --console-address ":9001"
      image: minio/minio
      ports:
      - '9000:9000'
      - '9001:9001'
      volumes:
      - 'minio_data:/data'
    createbuckets:
      image: minio/mc
      depends_on:
      - minio
      entrypoint: >
        /bin/sh -c "
        sleep 30;
        /usr/bin/mc config host add myminio http://minio:9000 minioadmin minioadmin;
        /usr/bin/mc mb --ignore-existing myminio/cvs;
        /usr/bin/mc cp --recursive ./dummy_data/ myminio/cvs/;
        exit 0;
        "
      volumes:
      - './backend/sample_data:/dummy_data'

volumes:
    minio_data:
        driver: local